<?php
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
//function info_about_university_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
//  // Remove the contextual links on all blocks that provide them.
//  dpm('test4');
//
//}

/**
 * Implements hook_views_query_alter().
 */

function info_about_university_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  // (Example assuming a view with an exposed filter on node title.)
  // If the input for the title filter is a positive integer, filter against
  // node ID instead of node title.


 // dpm($title);
  if ($view->id() == 'info_about_university') {
    $request     = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $title       = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'universityenglishname')) {

            $condition['value']=$title;
        }
      }
    }
  }
}
